package tn.esprit.jdbc.entities;

import java.sql.Timestamp;

public class Reclamation {
    private int reclamationId; // Auto-generated by the database
    private int userId; // Foreign key to the user who made the reclamation
    private String sujet;
    private String description;
    private Timestamp dateReclamation;
    private String reponseReclamation; // New field for the response

    // Default constructor
    public Reclamation() {
    }

    // Parameterized constructor
    public Reclamation(int userId, String sujet, String description) {
        this.userId = userId;
        this.sujet = sujet;
        this.description = description;
    }

    // Parameterized constructor with response
    public Reclamation(int reclamationId, int userId, String sujet, String description, String reponseReclamation) {
        this.reclamationId = reclamationId;
        this.userId = userId;
        this.sujet = sujet;
        this.description = description;
        this.reponseReclamation = reponseReclamation;
    }

    // Getters and Setters
    public int getReclamationId() {
        return reclamationId;
    }

    public void setReclamationId(int reclamationId) {
        this.reclamationId = reclamationId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getSujet() {
        return sujet;
    }

    public void setSujet(String sujet) {
        this.sujet = sujet;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getDateReclamation() {
        return dateReclamation;
    }

    public void setDateReclamation(Timestamp dateReclamation) {
        this.dateReclamation = dateReclamation;
    }

    public String getReponseReclamation() {
        return reponseReclamation;
    }

    public void setReponseReclamation(String reponseReclamation) {
        this.reponseReclamation = reponseReclamation;
    }

    @Override
    public String toString() {
        return "Reclamation{" +
                "reclamationId=" + reclamationId +
                ", userId=" + userId +
                ", sujet='" + sujet + '\'' +
                ", description='" + description + '\'' +
                ", dateReclamation=" + dateReclamation +
                ", reponseReclamation='" + reponseReclamation + '\'' +
                '}';
    }
}